export const ALBUMS_ACTION_START = "ALBUMS_ACTION_START";
export const ALBUMS_ACTION_ERROR = "ALBUMS_ACTION_ERROR";
export const ALBUMS_LOAD_SUCCESS = "ALBUMS_LOAD_SUCCESS";
export const UPDATE_FILTER = "UPDATE_FILTER";
